%IMPORTANT this function will overwrite annotations generated by previous
%runs. If you want to reannotate a folder, you have to reannotate
%EVERYTHING (e.g. calls, leds, etc.). It does NOT append to existing
%annotations. If that is your goal, use led2annot or call2annot separately

function annotDir(annotCalls, annotLed)
    while(1) %putting this in an infinite while loop let's the function easily be teriminated early
        directory = uigetdir; %open gui to select folder
        if directory == 0
            warning('no file selected, cancelled')
            break
        end

        videos = dir(strcat(directory, filesep, '*.mp4'));
        calls = dir(strcat(directory, filesep, '*.mat'));
        if isempty(calls)
            warning('there are no calls in this folder, function may not work as desired')
        end
        
        %this if block checks that the no. vidoes and no. call files line
        %up. Assumes that there should be either 1 or 2 vids for each call
        if not(length(videos) == length(calls) || length(videos)/2 == length(calls))
            choice = menu("number of videos and number of call files don't seem right. " + ...
            "Something may be wrong (e.g. no call files in folder, )" + ...
            "are you sure you want to continue?" ...
            ,'Y','N');
            if choice == 2 || choice == 0
               break;
            end
        end
        
        %Since RI box experiments save 2 videos, this only takes the front
        %facing videos
        if length(videos) == 2*length(calls)
            videos = dir(strcat(directory, filesep, '*ront.mp4'));
        end

        %Generate base annot files for each folder
        for i = 1:length(videos)
            foundAnnot(strcat(videos(i).folder, filesep, videos(i).name));
        end

        annots = dir(strcat(directory, filesep, '*.annot'));

        %If desired, annotate with calls
        if annotCalls
            for i = 1:length(annots)
                annot = strcat(directory, filesep, annots(i).name);
                call = strcat(directory, filesep, calls(i).name);
                call2annot(call, annot, annot);
            end
        end

        %If desired, annotate with leds
        if annotLed
            disp('Grab a snack, marking the LEDs takes awhile');
            for i = 1:length(annots)
                annot = strcat(directory, filesep, annots(i).name);
                vid = strcat(directory, filesep, videos(i).name);
                led2annot(vid, annot, annot);
            end
        end
        break
    end
end